/*
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1, 3
6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28
(
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over n divisors?

*/

function primeFactorization(n) {
    let factors = {}
    let i = 2
    while (i *i <= n) {
        if (n % i) {
            i++
        } else {
            n /= i;
            factors[i] = (factors[i] || 0) + 1;
        }
    }
    if (n > 1) {
        factors[n] = (factors[n] || 0) + 1;
    }
    return factors
}

function numDivisors(n) {
    let factors = primeFactorization(n);
    let total = 1;
    for (let factor in factors) {
        total *= factors[factor] + 1;
    }
    return total;
}

function divisibleTriangleNumber(n) {
    let i = 1
    let k = 2

    while (true) {
        if (numDivisors(i) >= n) {
            return i
        }
        i += k
        k++
    }
}