/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, 
find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
    let a = 0, b = 1
    let res = 0
    while (a <= n) {
        if (a % 2 == 0) {
            res += a
        }
        [a, b] = [b, a + b] 
    }
    return res
}

